rsa:
  public-key: classpath:/keys/public-key.pem
  private-key: classpath:/keys/private-key.pem

authentication:
  login-attempts-limit: 5
  error-message:
    invalid_credentials: "아이디 또는 비밀번호가 잘못되었습니다."
    exceeded_login_attempts: "로그인 시도 횟수를 초과하였습니다."

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  profiles:
    active: local

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  datasource:
    url: jdbc:h2:mem:local
    username: local
    password:
    driverClassName: org.h2.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        auto_quote_keyword: true

  h2:
    console:
      enabled: true

  docker:
    compose:
      file: docker-compose-redis.yml
